backend/poem/poem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from show import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # index
    path('', views.index, name='index'),
    path('category/<int:category_id>/', views.index, name='category'),
    
    # show app
    path('show/', include('show.urls', namespace="show")),
    
    # users app
    path('users/', include('users.urls', namespace="users"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/poem/show/urls.py
from django.urls import path
from . import views

app_name = 'show'

urlpatterns = [
    path('poem/<int:poem_id>/', views.poem, name="poem"),
    
    # System likes.
    path('like/<int:poem_id>', views.like, name="like"),

    # Savepoem
    path('save/<int:poem_id>/', views.save_poem, name="save_poem")
]

backend/poem/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('sign/', views.sign, name="sign"),
    path('profile/', views.profile, name="profile"),
    path('logout/', views.logout, name="logout")
]

backend/poem/show/models.py
from django.db import models
from users.models import User

# from time, for fnc date_count
from datetime import datetime
import time

# Для создание списка в поле модели.
from django.db.models import JSONField

class Category(models.Model):
    title = models.CharField(max_length=60)
    
    def __str__(self):
        return f'{self.title}'
    
class Poem(models.Model):
    title = models.CharField(max_length=120)
    text = models.TextField()
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, related_name='poems')
    date_public = models.DateTimeField(auto_now_add=True)
    like = models.ManyToManyField(to=User, related_name="poems", blank=True)
    reads = models.ManyToManyField(to=User, related_name="reads")
    
    def __str__(self):
        return f'{self.title}, {self.text} == {self.category}'

    def text_poem(self):
        dot = self.text.count('.')
        if dot > 1:
            total = self.text.find('.')
            total_str = self.text.find('.', total + 1)
            return f"{self.text[0:total_str + 1]}..."
        else:
            return self.text

    def date_count(self):
        now_date = self.date_public.date()
        today = datetime.today().date()

        delta = (today - now_date).days

        if delta == 0:
            return 'Сегодня'
        elif delta == 1:
            return 'Вчера'
        elif delta == 7:
            return 'Неделю назад'
        elif delta < 31:
            return f'{delta} дней назад'
        elif delta < 365:
            months = delta // 30
            return f'{months} месяц(ев) назад'
        else:
            years = delta // 365
            return f'{years} год(а/лет) назад'
        

# Filter for Comments.
class BadWords(models.Model):
    bad_words = models.CharField(max_length=120)
    
    def __str__(self):
        return f'{self.bad_words}'
        

# Manager model Comment
class ManagerComment(models.QuerySet):
    def checking(self, username):
        self.total = []
        for word in list(self):
            
            # Save username in list.
            self.total.append(str(word).split()[0])
        
        answer = set(self.total)
        if len(answer) == 1 and self.total[0] == username:
            return False
        return True
            
        
class Comment(models.Model):
    user = models.ForeignKey(to=User, related_name='comment', on_delete=models.CASCADE)
    poem = models.ForeignKey(to=Poem, related_name='comment', on_delete=models.CASCADE)
    date_public = models.DateTimeField(auto_now_add=True)
    text = models.CharField(max_length=250)
    
    # Connect.
    objects = ManagerComment.as_manager()
    
    def __str__(self):
        return f'{self.user} for poem'
    
    def text_poem(self):
        dot = self.text.count('.')
        if dot > 1:
            total = self.text.find('.')
            total_str = self.text.find('.', total + 1)
            return f"{self.text[0:total_str + 1]}..."
        else:
            return self.text
        
    def filters(self, text):

        banned_words = BadWords.objects.values_list('bad_words', flat=True)
        
        text_lower = text.lower()
        
        for word in banned_words:
            if word and word.lower() in text_lower:
                return False
        return True
    
    def max_comments(self):
        if Comment.objects.all()[-4:]:
            pass

class SavePoem(models.Model):
    poem = models.ForeignKey(to=Poem, on_delete=models.CASCADE, related_name='save_poems')
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='save_poems')
    
    def __str__(self):
        return f'{self.poem} for {self.user}'  

backend/poem/show/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    
    text = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'Введите сообщение'
    }))
    
    class Meta:
        model = Comment
        fields = ('text', )

backend/poem/show/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category, Poem, Comment, SavePoem
from django.contrib.auth.decorators import login_required
from .forms import CommentForm
from django.contrib import messages

def index(request, category_id=None):

    context = {
        'categoryies' : Category.objects.all(),
        'last_poem' : Poem.objects.filter(category_id=category_id) if category_id else Poem.objects.all().order_by('-id')[:3],
        'title' : Category.objects.get(id=category_id) if category_id else "Посдение посты"
    }
    
    return render(request, 'show/index.html', context)

def poem(request, poem_id):
    poem = Poem.objects.get(id=poem_id)
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            if not request.user.is_authenticated:
                
                messages.success(request, 'Для работы на сайте нужна Авторизация')
                return redirect('users:login')
            
            comment.user = request.user
            comment.poem = poem
            
            last_comment = poem.comment.order_by('-id')[:4]
        
            if last_comment.checking(request.user.username):
                if comment.filters(text=comment.text):
                    comment.save()
                else:
                    return messages.error(request, 'Вы не можете такое писать!')
            else:
                return messages.error(request, 'Вы не можете пока что писать!')

            return redirect(request.META.get('HTTP_REFERER', '/'))

        
    else:
        form = CommentForm()
    
    context = {
        'poem': poem,
        'form': form,
        'comments': reversed(Comment.objects.filter(poem_id=poem_id).order_by('-id')[:6]),
        'count_comment' : Comment.objects.filter(poem_id=poem_id).count(),
    }
    
    try:
        context['saved_poems'] = request.user.read_poems.all()[:3]
    except:
        context
    
    if request.user.is_authenticated:
        poem.reads.add(request.user)
        request.user.read_poems.add(poem)
    return render(request, 'show/poem.html', context)

# System likes.
@login_required
def like(request, poem_id):
    poem = Poem.objects.get(id=poem_id)
    context = {}
    if not request.user in poem.like.all():
        poem.like.add(request.user)
    else:
        poem.like.remove(request.user)
    return redirect(request.META['HTTP_REFERER'])

@login_required
def save_poem(request, poem_id):
    poem = get_object_or_404(Poem, id=poem_id)
    user = request.user
    poem_obj = SavePoem.objects.filter(poem=poem, user=user)
    
    if poem_obj.exists():
        poem_obj.delete()
    else:
        # Create objects
        SavePoem.objects.create(poem=poem, user=user)
    return redirect(request.META['HTTP_REFERER'])

backend/poem/show/templates/show/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Поэтический блог | Главная</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="header-inner">
                <div class="logo">
                    <a href="{% url "index" %}">Стихи и Душа</a>
                </div>
                <nav class="nav">
                    <ul>
                        <li><a href="{% url "index" %}">Главная</a></li>
                        <li><a href="#">О авторе</a></li>
                        <li><a href="#">Коллекции</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url "users:profile" %}">Профиль</a></li>
                        {% endif %}
                    </ul>
                </nav>
                <div class="auth">
                    {% if not user.is_authenticated %}
                        <a href="{% url "users:login" %}" class="btn btn-login">Войти</a>
                        <a href="{% url "users:sign" %}" class="btn btn-signup">Регистрация</a>
                    {% else %}
                        <a href="{% url "users:logout" %}" class="btn btn-signup">Выйти</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>

    {% if messages or form.errors %}
        <div class="message-box" id="custom-message-box">
            <div class="message-box-header">
                <div class="message-box-title">Важное сообщение</div>
                <button class="message-box-close" aria-label="Закрыть">&times;</button>
            </div>

            {% for message in messages %}
                <div class="alert {{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}

            {% if form.errors %}
                <div class="alert error">
                    <ul>
                        {% for field in form %}
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>
    {% endif %}

    {% block main %}

    {% endblock main %}

    <footer class="footer">
        <div class="container">
            <div class="footer-inner">
                <div class="footer-logo">
                    <a href="index.html">Стихи и Душа</a>
                </div>
                <div class="footer-links">
                    <ul>
                        <li><a href="#">О нас</a></li>
                        <li><a href="#">Контакты</a></li>
                        <li><a href="#">Правила</a></li>
                        <li><a href="#">Политика конфиденциальности</a></li>
                    </ul>
                </div>
                <div class="footer-social">
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
            <div class="copyright">
                &copy; 2025 Поэтический блог. Все права защищены.
            </div>
        </div>
    </footer>

    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

backend/poem/show/templates/show/index.html
{% extends "show/base.html" %}
{% load static %}

{% block main %}
    <main class="main">
        <div class="container">
            <section class="categories">
                <h2>Категории</h2>
                <div class="category-list">
                    <a href="{% url "index" %}" class="category">Все</a>
                    {% for category in categoryies %}
                        <a href="{% url "category" category.id %}" class="category">{{ category.title }}</a>
                    {% endfor %}
                </div>
            </section>

            <section class="poems">
                <h2>{{ title.title }}</h2>
                <div class="poem-grid">
                    {% for poems in last_poem %}
                        <article class="poem-card">
                            <div class="poem-meta">
                                <span class="date">{{ poems.date_count }}</span>
                                <span class="category">{{ poems.category }}</span>
                            </div>
                            <h3 class="poem-title"><a href="{% url "show:poem" poems.id %}">{{ poems.title }}</a></h3>
                            <div class="poem-excerpt">
                                <p>{{ poems.text_poem }}<br>
                                </p>
                            </div>
                            <div class="poem-footer">
                                <a href="{% url "show:poem" poems.id %}" class="read-more">Читать далее</a>
                                {% if user in poems.like.all %}
                                    <a class="red" href="{% url "show:like" poems.id %}">
                                        <i class="far fa-heart"></i> {{ poems.like.count }}
                                    </a>
                                {% else %}
                                    <a class="likes" href="{% url "show:like" poems.id %}">
                                        <i class="far fa-heart"></i> {{ poems.like.count }}
                                    </a>
                                {% endif %}
                            </div>
                        </article>
                    {% endfor %}
                </div>
            </section>
        </div>
    </main>
{% endblock main %}

backend/poem/show/templates/show/poem.html
{% extends "show/base.html" %}
{% load static %}

{% block main %}
    <main class="main poem-page">
        <div class="container">
            <article class="poem-full">
                <div class="poem-meta">
                    <span class="date">{{ poem.date_count }}</span>
                    <span class="category">{{ poem.category }}</span>
                </div>
                <h1 class="poem-title">{{ poem.title }}</h1>
                <div class="poem-author">
                    <img src="{% static "img/author.jpg" %}" alt="Автор" class="author-avatar">
                    <span class="author-name">Rita D.</span>
                </div>
                <div class="poem-content">
                    <p>{{ poem.text }}<br>
                    
                    </p>
                </div>
                <div class="poem-actions">

                    {% comment %} Logic like {% endcomment %}
                    {% if user in poem.like.all %}
                        <a class="red" href="{% url "show:like" poem.id %}">
                            <i class="far fa-heart"></i> {{ poem.like.count }}
                        </a>
                    {% else %}
                        <a class="likes" href="{% url "show:like" poem.id %}">
                            <i class="far fa-heart"></i> {{ poem.like.count }}
                        </a>
                    {% endif %}

                    {% comment %} Logic poem {% endcomment %}
                    {% if poem.id in saved_poems %}
                        <a class="btn-bookmark gold" href="{% url "show:save_poem" poem.id %}">
                            <i class="far fa-bookmark"></i> В закладки
                        </a>
                    {% else %}
                        <a class="btn-bookmark" href="{% url "show:save_poem" poem.id %}">
                            <i class="far fa-bookmark"></i> В закладки
                        </a>
                    {% endif %}
                    
                    <div class="share">
                        <button id="copy-link-btn" class="copy-button">📎 Поделиться: скопировать ссылку</button>
                        <span id="copy-confirm" class="copy-confirm">Ссылка скопирована!</span>
                    </div>

                </div>
            </article>

            <section class="comments">
                <h2>Комментарии ({{ count_comment }})</h2>
                <form class="comment-form" method="POST" action="{% url "show:poem" poem.id %}">
                    {% csrf_token %}
                    {{ form.text }}
                    <button type="submit" class="btn btn-submit">Отправить</button>
                </form>
                <div class="comment-list">
                    {% for comment in comments %}
                        <div class="comment">
                            <div class="comment-author">
                                {% comment %} time {% endcomment %}
                                <img src="{% if comment.user.image %} {{ comment.user.image.url }} {% else %} {% static "img/author.jpg" %} {% endif %}" alt="Пользователь" class="comment-avatar">
                                <span class="comment-name">{{ comment.user.username }}</span>
                                <span class="comment-date">{{ comment.date_count }}</span>
                            </div>
                            <div class="comment-text">
                                {{ comment.text }}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </section>
        </div>

        {% if saved_poems %}
            <h2>Просмотренные ранее стихи</h2>
            <div class="poem-grid">
                {% for poems in saved_poems %}
                    {% if not poems == poem %}
                        <article class="poem-card">
                            <div class="poem-meta">
                                <span class="date">{{ poems.date_count }}</span>
                                <span class="category">{{ poems.category }}</span>
                            </div>
                            <h3 class="poem-title"><a href="poem.html">{{ poems.title }}</a></h3>
                            <div class="poem-excerpt">
                                <p>{{ poems.text_poem }}<br>
                                </p>
                            </div>
                            <div class="poem-footer">
                                <a href="{% url "show:poem" poems.id %}" class="read-more">Перейти</a>
                                {% if user in poems.like.all %}
                                    <a class="red" href="{% url "show:like" poems.id %}">
                                        <i class="far fa-heart"></i> {{ poems.like.count }}
                                    </a>
                                {% else %}
                                    <a class="likes" href="{% url "show:like" poems.id %}">
                                        <i class="far fa-heart"></i> {{ poems.like.count }}
                                    </a>
                                {% endif %}
                            </div>
                        </article>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
    </main>
{% endblock main %}